# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
          node-version: 12          
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
          args: deploy
      env:
        FIREBASE_TOKEN:  ${{secrets.CLE_FIREBASE}}
